### ISSUE TITLE
Reconsider private setters

### ISSUE THREAD

**Issue by mpmenne** [vdmpeniel/Mario#2]
Hey so nice job making `CoinSet` private in `CoinSelector`.  That class looks really clean.

My only suggestion is to consider not using the private setter for `coinSet`.  In Java, the convention is to only use that are public.  I just automatically assumed the setter was public and didn't see that it was private until second or third glance.

**Comment by vdmpeniel** [comment]
I actually hesitated when making it private, it didn't feel right. Thank you for the advice!!!!
