### ISSUE TITLE
Only define one Spring context

### ISSUE THREAD

**Issue by mpmenne** [vdmpeniel/Mario#5]
Hey so that's a pretty clever way of getting the beans out of the context file that I had never thought of before.  Fortunately, there's an easier way.

In a Spring program, you'll only have to define the application context once.  After the context is defined, you just need to grab one bean from the context and you're good to go.  

The cool thing about Spring is that once you start using [setter and constructor injection](http://www.tutorialspoint.com/spring/setter_based_dependency_injection.htm) everything your class needs is automatically built and injected into your class.

In Greedy it may be difficult to see the value of injection, but you'll definitely see it more in the next pset!

**Comment by vdmpeniel** [comment]
I am trying to understand this: You want me to define the application context only once. OK let me see how that works. I am detail oriented normally, but in this special case the purpose of me persistently following through all this little details is actually really wrapping my head around this concepts. Thanks!
