### ISSUE TITLE
Be careful with prototype

### ISSUE THREAD

**Issue by mpmenne** [vdmpeniel/Mario#6]
In your `beans.xml` be sure to be careful with using prototype.

`prototype` says that it will make many copies of that bean from a single class definition.  Typically in an application we want one bean that we will use over and over again throughout the application.

The reason for this is that most of the time we are using Spring to avoid the singleton pattern.  One of the main benefits of Spring is for us to have an object that can be used everywhere, without any of the [downsides of a singleton](http://stackoverflow.com/questions/137975/what-is-so-bad-about-singletons).

The next pset is a great place to use Spring.  Looking forward to what you come up with!

**Comment by vdmpeniel** [comment]
Thank you Mike, for your time and the link. I understood the downsides of the singletons and the reasons for using spring in instead. Have a beautiful weekend!Vic :D 

```
El Jueves 1 de septiembre de 2016 0:00, Mike Menne <notifications@github.com> escribió:
```

 In your beans.xml be sure to be careful with using prototype.prototype says that it will make many copies of that bean from a single class definition. Typically in an application we want one bean that we will use over and over again throughout the application.The reason for this is that most of the time we are using Spring to avoid the singleton pattern. One of the main benefits of Spring is for us to have an object that can be used everywhere, without any of the downsides of a singleton.The next pset is a great place to use Spring. Looking forward to what you come up with!—
